### ISSUE TITLE
A Reflected XSS Vulnerability in wordpress plugin "Raygun4WP 1.8.0.0"

### ISSUE THREAD

**Issue by jgj212** [MindscapeHQ/raygun4wordpress#16]
Hello：
    I found a Reflected XSS Vulnerability in wordpress plugin "Raygun4WP 1.8.0.0" which is developmented by your company, this plugin can be downloaded at wordpress plugin website "https://wordpress.org/plugins/raygun4wp/".
  How can i send this vulnerability report to you to fix it. My Email is jgj212@gmail.com.

**Comment by BenjaminHarding** [comment]
Closing as I believe this was resolved in #17
