### ISSUE TITLE
Prevent rgisanonymous cookie from being set

### ISSUE THREAD

**Issue by seandrickson** [MindscapeHQ/raygun4wordpress#23]
Because the RaygunClient initialization isn't passing in the user tracking setting, the Raygun PHP client is setting a cookie on every request:
here: https://github.com/MindscapeHQ/raygun4wordpress/blob/master/main.php#L148
and here: https://github.com/MindscapeHQ/raygun4wordpress/blob/master/main.php#L169

Should have something like:
```php
$client = new Raygun4php\RaygunClient(get_option('rg4wp_apikey'), rg4wp_useAsyncSending(), get_option('rg4wp_usertracking'));
```

This prevents the "SetUser" function from running in the raygun4php function here:
https://github.com/MindscapeHQ/raygun4php/blob/master/src/Raygun4php/RaygunClient.php#L158

**Comment by CmdrKeen** [comment]
Thanks for reporting this @seandrickson, we'll have a team member look into improving this. Thanks!

**Comment by seandrickson** [comment]
@BenjaminHarding new version looks good! I'll try it out in our install. Thank you.

Closing issue.
