### ISSUE TITLE
New Raygun version

### ISSUE THREAD

**Issue by Androlax2** [MindscapeHQ/raygun4wordpress#34]
Hey,

I updated the package on a fork : https://github.com/Androlax2/raygun4wordpress

If you want to take look and maybe do something like that to update this plugin ^^

Just followed the documentation https://raygun.com/documentation/language-guides/php/crash-reporting/installation

**Comment by Olwiba** [comment]
Great work on this @Androlax2 - the fork you've made looks really good 🤩
I've got this in our pipeline but looks like you'll be able to use your fork for the time being.

Always love seeing community submissions on our OSS & I'd love to say thank you!
Send me an email at `ollie@raygun.com` and we can get a goodie box sent out to you 😄

**Comment by Androlax2** [comment]
Thanks you @Olwiba ! I sent you an email aha, if you need more informations don't hesitate to PM me

**Comment by redJ4y** [comment]
Your contributions will be included in Raygun for WordPress version 2.0.0! We really appreciate it 😄
